# sudo docker build -t  registry.hamdocker.ir/ask-your-sister/portfolio-c:v1 -f ./Dockerfile-deploy .  
# sudo docker push registry.hamdocker.ir/ask-your-sister/portfolio-c:v1  

FROM ghcr.io/milad75rasouli/portfolio:latest
COPY ./config.toml /app/config.toml