// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/Milad75Rasouli/portfolio/frontend/views/layouts"
import "fmt"

func Blog(blogID string, email string, role string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layouts.Base("Blog", fmt.Sprintf(`
<div class="b-content-divider b-content-divider-day b-content-vr col p-0">
  <div class="container h-100">
      <div class="row h-100 align-hv-center">
          <div class="overflow-auto pt-3 pb-3 p-4 border border-light bg-opacity-75 text-start bg-dark blogs-list">
            <h1>Title</h1>   
            <p>Here are you information Email=%s Role=%s </p>
            <p>You asked for %s blog</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
            <p>dsf</p>
          </div>
      </div>
      </div>
  </div>
</div>`, email, role, blogID)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
