// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/Milad75Rasouli/portfolio/internal/model"
import "github.com/Milad75Rasouli/portfolio/frontend/views/layouts"
import "fmt"

func Home(home model.Home) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layouts.Base("Milad Rasouli", fmt.Sprintf(`
    <div class="b-content-divider b-content-divider-day b-content-vr col">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-xl-2 col-lg-1 col-md-0"></div>
                    <div class="col-xl-8 col-lg-10 col-md-12 align-hv-center">
                        <div class="the-content justify-content-center align-items-center">
                            <p class="title">%s</p>
                            <p class="interval-text">%s</p>
                            <p class="summary summary-day">%s</p>
                            <a href="%s" class="btn btn-dark">My Github</a>
                            <!-- <button class="btn btn-outline-dark">Here</button> -->
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-1 col-md-0"></div>
                </div>
            </div>
    </div>
    `, home.Name, home.Slogan, home.ShortIntro, home.GithubUrl)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
