// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/Milad75Rasouli/portfolio/frontend/views/layouts"

func SignIn() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layouts.Base("Sgin In", `
    <div class="b-content-divider b-content-divider-day b-content-vr col">
        <div class="container h-100">

        <div class="container h-100">
        <div class="row h-100 align-hv-center">
            <div class="main-form text-start">
                <div class="card-header text-center border-bottom border-3 border-light">
                    <h1>Sign In</h1>
                </div>
                <div class="card-body">
                    <form id="signin-form" action="/sign-in" method="post">
                        <div class="form-group mt-2">
                            <label for="email">Email:</label>
                            <input type="email" class="form-control form-control-day bg-light border-secondary text-dark" id="email" name="email" placeholder="Email" required/>
                        </div>
                        <div class="form-group mt-2">
                            <label for="password">Password:</label>
                            <input type="password" class="form-control form-control-day bg-light border-secondary text-dark" id="password" name="password" placeholder="Password" required/>
                        </div>
                        <div class="mt-2">  
                            <button type="submit" class="btn btn-dark float-start">Sign in</button>
                            <button type="button" class="btn btn-dark float-end">Sign in with Github</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        </div>
        </div>
    </div>
    <script>
    document.getElementById('signin-form').addEventListener('submit', function(e) {
        e.preventDefault();
        var formData = {
            email: document.getElementById('email').value,
            password: document.getElementById('password').value
        };
        fetch('/user/sign-in', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(formData)
        })
        .then(response => {
            if (response.redirected) {
                window.location.href = response.url; // Redirect to the new URL
            } else {
                return response.json();
            }
        })
        .then(data => {
            if (data && data.message !== undefined) {
                var notification = document.getElementById('notification');
                notification.textContent = data.message;
                notification.style.display = 'block';
                setTimeout(function() {
                    notification.style.display = 'none';
                }, 5000);
            } else {
                // Handle success, such as redirecting to another page
            }
        })
        .catch((error) => {
            console.error('Error:', error);
        });
    });
    </script>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
